# noinspection SqlNoDataSourceInspectionForFile

-- MySQL Script generated by MySQL Workbench
-- Wed Oct  5 22:16:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smartcity
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smartcity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartcity` DEFAULT CHARACTER SET utf8 ;
USE `smartcity` ;

-- -----------------------------------------------------
-- Table `smartcity`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartcity`.role ;

CREATE TABLE IF NOT EXISTS `smartcity`.role(
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(65) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartCity`.`serviceTask_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartcity`.`roles_users` ;

CREATE TABLE IF NOT EXISTS `smartcity`.`roles_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_roles_users_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_roles_users_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_roles_users_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `smartcity`.user (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_users_role1`
    FOREIGN KEY (`id`)
    REFERENCES `smartcity`.role (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartcity`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartcity`.user ;

CREATE TABLE IF NOT EXISTS `smartcity`.user(
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(65) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `active` BOOLEAN DEFAULT TRUE,
  `confirmed_at` DATETIME,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `smartcity`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartCity`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartcity`.`ticket` ;

CREATE TABLE IF NOT EXISTS `smartcity`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `description` TEXT(2048) NOT NULL,
  `state` ENUM('DONE', 'WORK_IN_PROGRESS', 'PLANNED', 'NEW') NOT NULL DEFAULT 'NEW',
  `image_path` VARCHAR(200) NULL,
  `reporter_id` INT NOT NULL,
  `assignee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_users1_idx` (`reporter_id` ASC) VISIBLE,
  INDEX `fk_ticket_users2_idx` (`assignee_id` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_users1`
    FOREIGN KEY (`reporter_id`)
    REFERENCES `smartcity`.user (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_users2`
    FOREIGN KEY (`assignee_id`)
    REFERENCES `smartcity`.user (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartCity`.`serviceTask`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartcity`.service_task ;

CREATE TABLE IF NOT EXISTS `smartcity`.service_task (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT(1000) NOT NULL,
  `days_to_complete` INT NULL,
  `state` ENUM('DONE', 'WORK_IN_PROGRESS', 'PLANNED', 'NEW') NOT NULL DEFAULT 'NEW',
  `man_hours` INT NULL DEFAULT 0,
  `creator_id` INT NOT NULL,
  `parent_ticket` INT NOT NULL,
  `cost` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_serviceTask_users1_idx` (`creator_id` ASC) VISIBLE,
  INDEX `fk_serviceTask_ticket1_idx` (`parent_ticket` ASC) VISIBLE,
  CONSTRAINT `fk_serviceTask_users1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `smartcity`.user (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serviceTask_ticket1`
    FOREIGN KEY (`parent_ticket`)
    REFERENCES `smartcity`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartCity`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartcity`.`comment` ;

CREATE TABLE IF NOT EXISTS `smartcity`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT(1000) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `ticket_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_ticket_idx` (`ticket_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_ticket`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `smartcity`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartCity`.`serviceTask_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartcity`.`service_task_has_users` ;

CREATE TABLE IF NOT EXISTS `smartcity`.`service_task_has_users` (
  `service_task_id` INT NOT NULL,
  `worker_id` INT NOT NULL,
  PRIMARY KEY (`service_task_id`, `worker_id`),
  INDEX `fk_service_task_has_users_users1_idx` (`worker_id` ASC) VISIBLE,
  INDEX `fk_service_task_has_users_service_task1_idx` (`service_task_id` ASC) VISIBLE,
  CONSTRAINT `fk_service_task_has_users_service_task1`
    FOREIGN KEY (`service_task_id`)
    REFERENCES `smartcity`.service_task (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_task_has_users_users1`
    FOREIGN KEY (`worker_id`)
    REFERENCES `smartcity`.user (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO role (name, description)
VALUES ('Resident', 'Normal Resident');
INSERT INTO role (name, description)
VALUES ('Technician', 'Service Technician');
INSERT INTO role (name, description)
VALUES ('Manager', 'City Manager');
INSERT INTO role (name, description)
VALUES ('Admin', 'System admin');

INSERT INTO user (email, password, name, surname, role_id)
VALUES ('admin@smartcity.com', 'admin', 'John', 'Doe', 4);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
