-- MySQL Script generated by MySQL Workbench
-- Wed Oct  5 22:16:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smartCity
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smartCity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartCity` DEFAULT CHARACTER SET utf8 ;
USE `smartCity` ;

-- -----------------------------------------------------
-- Table `smartCity`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartCity`.`users` ;

CREATE TABLE IF NOT EXISTS `smartCity`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(65) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartCity`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartCity`.`ticket` ;

CREATE TABLE IF NOT EXISTS `smartCity`.`ticket` (
  `ticketId` INT NOT NULL AUTO_INCREMENT,
  `ticketName` VARCHAR(64) NOT NULL,
  `ticketDescription` TEXT(2048) NOT NULL,
  `ticketState` ENUM('DONE', 'WORK_IN_PROGRESS', 'PLANNED', 'NEW') NOT NULL DEFAULT 'NEW',
  `imagePath` VARCHAR(200) NULL,
  `reporterId` INT NOT NULL,
  `assigneeId` INT NOT NULL,
  PRIMARY KEY (`ticketId`),
  INDEX `fk_ticket_users1_idx` (`reporterId` ASC) VISIBLE,
  INDEX `fk_ticket_users2_idx` (`assigneeId` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_users1`
    FOREIGN KEY (`reporterId`)
    REFERENCES `smartCity`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_users2`
    FOREIGN KEY (`assigneeId`)
    REFERENCES `smartCity`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartCity`.`serviceTask`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartCity`.`serviceTask` ;

CREATE TABLE IF NOT EXISTS `smartCity`.`serviceTask` (
  `taskId` INT NOT NULL AUTO_INCREMENT,
  `taskDescription` TEXT(1000) NOT NULL,
  `daysToComplete` INT NULL,
  `taskState` ENUM('DONE', 'WORK_IN_PROGRESS', 'PLANNED', 'NEW') NOT NULL DEFAULT 'NEW',
  `manHours` INT NULL DEFAULT 0,
  `creatorId` INT NOT NULL,
  `parentTicket` INT NOT NULL,
  `cost` INT NULL,
  PRIMARY KEY (`taskId`),
  INDEX `fk_serviceTask_users1_idx` (`creatorId` ASC) VISIBLE,
  INDEX `fk_serviceTask_ticket1_idx` (`parentTicket` ASC) VISIBLE,
  CONSTRAINT `fk_serviceTask_users1`
    FOREIGN KEY (`creatorId`)
    REFERENCES `smartCity`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serviceTask_ticket1`
    FOREIGN KEY (`parentTicket`)
    REFERENCES `smartCity`.`ticket` (`ticketId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartCity`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartCity`.`comments` ;

CREATE TABLE IF NOT EXISTS `smartCity`.`comments` (
  `commentId` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT(1000) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `ticket_ticketId` INT NOT NULL,
  PRIMARY KEY (`commentId`),
  INDEX `fk_comments_ticket_idx` (`ticket_ticketId` ASC) VISIBLE,
  CONSTRAINT `fk_comments_ticket`
    FOREIGN KEY (`ticket_ticketId`)
    REFERENCES `smartCity`.`ticket` (`ticketId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartCity`.`serviceTask_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartCity`.`serviceTask_has_users` ;

CREATE TABLE IF NOT EXISTS `smartCity`.`serviceTask_has_users` (
  `serviceTask_taskId` INT NOT NULL,
  `workerId` INT NOT NULL,
  PRIMARY KEY (`serviceTask_taskId`, `workerId`),
  INDEX `fk_serviceTask_has_users_users1_idx` (`workerId` ASC) VISIBLE,
  INDEX `fk_serviceTask_has_users_serviceTask1_idx` (`serviceTask_taskId` ASC) VISIBLE,
  CONSTRAINT `fk_serviceTask_has_users_serviceTask1`
    FOREIGN KEY (`serviceTask_taskId`)
    REFERENCES `smartCity`.`serviceTask` (`taskId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serviceTask_has_users_users1`
    FOREIGN KEY (`workerId`)
    REFERENCES `smartCity`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
